-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT '41f44e68d0c27326' HASH '32c27d2719a5214bde57330e221a22004b7ca2776e0b36aab47fdfe6da824296' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."TB_MANAGER"(
    "PERMISSION" BOOLEAN NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "CONTACT" CHARACTER VARYING(255),
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."TB_MANAGER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TB_MANAGER;              
CREATE MEMORY TABLE "PUBLIC"."TB_PATIENT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 13) NOT NULL,
    "ADDRESS" CHARACTER VARYING(255),
    "BIRTH_DAY" CHARACTER VARYING(255),
    "CONTACT" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."TB_PATIENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");   
-- 12 +/- SELECT COUNT(*) FROM PUBLIC.TB_PATIENT;             
INSERT INTO "PUBLIC"."TB_PATIENT" VALUES
(1, 'Rua Canada, n45', '10/08/1994', '(15) 98546-2079', 'Sandro Almeida'),
(2, 'Rua Brazil, n121', '20/07/1994', '(15) 99653-1820', 'Marina Silva'),
(3, 'Rua Alaska, n361', '16/06/1994', '(15) 99845-1478', U&'Carlos Beltr\00e3o'),
(4, 'Rua Jamaica, n87', '12/05/1994', '(15) 99475-8525', 'Leticia Carmargo'),
(5, U&'Rua Fern\00e3o, n19', '03/04/1994', '(15) 99333-6932', 'Patricia Silver'),
(6, U&'Rua S\00e3o Paulo, n89', '09/03/1994', '(15) 99365-4785', 'Camila Teles'),
(7, 'Rua Lopes, n36', '13/02/1994', '(15) 99253-5565', 'Anderson Marson'),
(8, 'Rua Miriam, n465', '14/01/1994', '(15) 99365-6632', 'Freitas Pereira'),
(9, 'Rua EUA, n265', '19/12/1994', '(15) 99456-9859', 'Alex Azevedo'),
(10, 'Rua Canada, n51', '20/11/1994', '(15) 99485-0203', 'Silva Almeida'),
(11, U&'Rua Azerbaij\00e3o, n165', '21/10/1994', '(15) 99498-2521', 'Julio Castro'),
(12, 'Rua Felipinas, n165', '21/10/1994', '(15) 98393-2621', U&'Mirela Leit\00e3o Castro');      
CREATE MEMORY TABLE "PUBLIC"."TB_PROFESSIONAL"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "CONTACT" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "SPECIALTY" CHARACTER VARYING(255)
);               
ALTER TABLE "PUBLIC"."TB_PROFESSIONAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");              
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.TB_PROFESSIONAL;         
INSERT INTO "PUBLIC"."TB_PROFESSIONAL" VALUES
(1, '(15) 98965-7895', U&'Luana Silva Assun\00e7\00e3o', 'Audiologia'),
(2, '(15) 94758-4656', 'Clara Almeida Teles', 'Linguagem'),
(3, '(15) 99856-6985', 'Leticia Farias Assad', 'Voz'),
(4, '(15) 97856-8745', 'Leila Fagundes Silva', 'Disfagia'),
(5, '(15) 98974-6584', U&'Laura Pereira Beltr\00e3o', 'Fonoaudiologia Escolar');    
CREATE MEMORY TABLE "PUBLIC"."TB_REPORT"(
    "DATE_REPORT" TIMESTAMP(6),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "PATIENT_ID" BIGINT,
    "PROFESSIONAL_ID" BIGINT,
    "DESCRIPTION" CHARACTER VARYING,
    "REPORT_TYPE" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."TB_REPORT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");    
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.TB_REPORT;               
INSERT INTO "PUBLIC"."TB_REPORT" VALUES
(TIMESTAMP '2024-11-09 09:16:00', 1, 1, 1, U&'Queixa Principal: Dificuldade em ouvir em ambientes ruidosos e diminui\00e7\00e3o da audi\00e7\00e3o em altas frequ\00eancias. Hist\00f3rico: O paciente relata perda auditiva progressiva h\00e1 aproximadamente 5 anos, sem causa aparente. Nega o uso de otot\00f3xicos e hist\00f3rico de otites. Exames Realizados: Audiometria tonal limiar: Perda auditiva neurosensorial moderada, sim\00e9trica, com maior comprometimento nas altas frequ\00eancias. Logoaudiometria: Compreens\00e3o da fala adequada para o n\00edvel de perda auditiva. Impedanciometria: Curvas tipo A bilateralmente, sugerindo fun\00e7\00e3o timp\00e2nica normal. Diagn\00f3stico: Perda auditiva neurosensorial bilateral, presbiac\00fastica. Conduta: Orientar o paciente sobre a natureza da perda auditiva e a import\00e2ncia do uso de aparelhos auditivos. Realizar moldagem auricular para confec\00e7\00e3o de aparelhos auditivos. Acompanhamento peri\00f3dico para ajuste e verifica\00e7\00e3o da efic\00e1cia dos aparelhos. Considera\00e7\00f5es: O paciente apresenta bom potencial de reabilita\00e7\00e3o auditiva com o uso de aparelhos auditivos. Recomenda-se o acompanhamento regular com o fonoaudi\00f3logo para otimiza\00e7\00e3o da reabilita\00e7\00e3o.', 'AVALIATIVO'),
(TIMESTAMP '2024-12-09 09:16:00', 2, 1, 1, U&'Analise: Melhoria na em ouvir em ambientes ruidosos e diminui\00e7\00e3o da audi\00e7\00e3o em altas frequ\00eancias. Hist\00f3rico: O paciente relata certa recupera\00e7\00e3o auditiva progressiva. Exames Realizados: Audiometria tonal limiarrecupera\00e7\00e3o de 25%', 'EVOLUTIVO'); 
CREATE MEMORY TABLE "PUBLIC"."TB_SCHEDULING"(
    "IS_CANCEL" BOOLEAN NOT NULL,
    "IS_CONFIRMED" BOOLEAN NOT NULL,
    "IS_PRESENT" BOOLEAN NOT NULL,
    "DATE_HOUR" TIMESTAMP(6),
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 8) NOT NULL,
    "PATIENT_ID" BIGINT,
    "PROFESSIONAL_ID" BIGINT
);
ALTER TABLE "PUBLIC"."TB_SCHEDULING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.TB_SCHEDULING;           
INSERT INTO "PUBLIC"."TB_SCHEDULING" VALUES
(FALSE, TRUE, TRUE, TIMESTAMP '2024-09-10 10:14:00', 1, 5, 1),
(TRUE, FALSE, FALSE, TIMESTAMP '2024-10-10 10:14:00', 2, 5, 1),
(FALSE, TRUE, FALSE, TIMESTAMP '2024-11-10 10:14:00', 3, 5, 1),
(FALSE, FALSE, FALSE, TIMESTAMP '2024-11-11 13:14:00', 4, 4, 2),
(FALSE, TRUE, FALSE, TIMESTAMP '2024-11-13 07:14:00', 5, 3, 3),
(FALSE, FALSE, FALSE, TIMESTAMP '2024-11-14 08:14:00', 6, 2, 4),
(FALSE, TRUE, FALSE, TIMESTAMP '2024-11-15 09:14:00', 7, 1, 5);           
ALTER TABLE "PUBLIC"."TB_SCHEDULING" ADD CONSTRAINT "PUBLIC"."FK8GBNA3F1MOWEAQ6WFQXE18QDJ" FOREIGN KEY("PROFESSIONAL_ID") REFERENCES "PUBLIC"."TB_PROFESSIONAL"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."TB_REPORT" ADD CONSTRAINT "PUBLIC"."FKQME7QFCSASHAV75LPNF64IQIS" FOREIGN KEY("PATIENT_ID") REFERENCES "PUBLIC"."TB_PATIENT"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."TB_SCHEDULING" ADD CONSTRAINT "PUBLIC"."FKIRN1OV359ON433HJNDE9QO31J" FOREIGN KEY("PATIENT_ID") REFERENCES "PUBLIC"."TB_PATIENT"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."TB_REPORT" ADD CONSTRAINT "PUBLIC"."FKCRXU8FPOGCMPSKUBC2BWWWVQ8" FOREIGN KEY("PROFESSIONAL_ID") REFERENCES "PUBLIC"."TB_PROFESSIONAL"("ID") NOCHECK;    
